name: Build Commands and Create Release

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  inject-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download source.lua and version
        run: |
          curl -s https://raw.githubusercontent.com/EdgeIY/infiniteyield/refs/heads/master/source -o src/source.lua
          curl -s https://raw.githubusercontent.com/EdgeIY/infiniteyield/refs/heads/master/version -o version.json

      - name: Parse version
        id: get_version
        run: |
          VERSION=$(jq -r '.Version' version.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Download preinjected commands
        run: |
          curl -s https://raw.githubusercontent.com/jacklebeignet/zero-yield/refs/heads/main/preinjected.lua -o preinjected.lua

      - name: Modify and inject
        run: |
          VERSION=${{ steps.get_version.outputs.version }}

          # Replace all "Infinite" with "Zero"
          sed -i 's/Infinite/Zero/g' src/source.lua

          # Replace internal version assignment
          sed -i "s/Version[:=] *['\"]\\?[0-9.]*['\"]\\?/Version = \"$VERSION\"/g" src/source.lua

          # Prepend version comment
          sed -i "1i-- Version: $VERSION" src/source.lua

          # Append injected commands
          cat preinjected.lua >> src/source.lua

          # Write minified version to src/build.lua with a header comment
          {
            echo "-- This file is generated automatically and is not meant to be modified."
            sed '/^\s*$/d;s/^\s*//;s/\s*$//' src/source.lua
          } > src/build.lua

      - name: Commit updated src files to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/source.lua src/build.lua
          git commit -m "Updated Zero Yield to v${{ steps.get_version.outputs.version }}"
          git push

      - name: Create GitHub release and clean up
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo -e "## What’s New\n\n- Updated Zero Yield to version $VERSION" > notes.md
          gh release create "$VERSION" src/build.lua --title "$VERSION" --notes-file notes.md
          rm notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
